### ISSUE TITLE
juju 2.1 binary changed,txjuju needs to compensate

### ISSUE THREAD

**Issue by dpb1** [juju/txjuju#38]
```
Dec 16 17:41:08 job-handler-1 INFO  OS env:
{'HOME': '/var/lib/landscape',
 'JUJU_DATA': '/var/lib/landscape/juju-homes/1',
 'LANDSCAPE_CONFIG': 'standalone-1',
 'LANG': 'C',
 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games',
 'PWD': '/',
 'SHLVL': '1',
 'STORM_CEXTENSIONS': '1',
 'TZ': 'UTC',
 '_': '/sbin/start-stop-daemon',
 '_SYSTEMCTL_SKIP_REDIRECT': 'true'} Dec 16 17:41:08 job-handler-1 CRIT  Unhandled Error
Traceback (most recent call last):
Failure: txjuju.errors.CLIError: juju ended with exit code 1 (out='', err='Upon execvpe juju-2.0 ['juju-2.0', 'bootstrap', '-v', '--no-gui', '--to', 'bierstadt', '--auto-upgrade=fal se', '--config', '/var/lib/landscape/juju-homes/1/bootstrap.yaml', 'landscape-maas', '1'] in environment id 140155302643424
:Traceback  (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 430, in _fork
    environment  )
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 508, in _execChild
    os.execvpe(executable, args, e  nvironment)
  File "/usr/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.  py", line 382, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
')  Dec 16 17:41:08 job-handler-1 ERR  Failed to execute job: juju ended with exit code 1 (out='', err='Upon execvpe juju-2.0 ['juju-2.0', 'b  ootstrap', '-v', '--no-gui', '--to', 'bierstadt', '--auto-upgrade=false', '--config', '/var/lib/landscape/juju-homes/1/bootstrap.yaml', '  landscape-maas', '1'] in environment id 140155302643424
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-package  s/twisted/internet/process.py", line 430, in _fork
    environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/proce  ss.py", line 508, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 355, in execv  pe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 382, in _execvpe
    func(fullname, *argrest)
OSErro  r: [Errno 2] No such file or directory
')
Traceback (most recent call last):
  File "/opt/canonical/landscape/canonical/landscape/model/activity/jobrunner.py", line 40, in run
    yield self._run_activity(account_id, activity_id)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/canonical/landscape/canonical/landscape/model/juju/jobs.py", line 153, in _run_activity
    cloud_name="landscape-maas")
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/txjuju/cli.py", line 459, in _handle_success
    raise error
CLIError: juju ended with exit code 1 (out='', err='Upon execvpe juju-2.0 ['juju-2.0', 'bootstrap', '-v', '--no-gui', '--to', 'bierstadt', '--auto-upgrade=false', '--config', '/var/lib/landscape/juju-homes/1/bootstrap.yaml', 'landscape-maas', '1'] in environment id 140155302643424
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 430, in _fork
    environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 508, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 382, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
')
```

Ideas:

Think we need to just use 'juju', and perhaps make sure the package conflicts with juju-1-default

**Comment by freeekanayaka** [comment]
Is this backward incompatible change mentioned in the release notes? If notes, we should ask to add it.

Also, if there's no compelling reason to not do so, I argue they should have left a juju-2.0 symlink and print a deprecation warning.

Let's bear in mind that if juju following semantic versioning (as it appears they do), incomp

**Comment by dpb1** [comment]
Filed this as well.  https://bugs.launchpad.net/juju/+bug/1650644
